---
- name: prepare controlnode for part 6
  hosts: controlnode

  tasks:
    - name: prepare part 6
      copy:
        src: demo-5.py
        dest: /home/vagrant/library/demo.py
      loop_control:
        label: "{{ item.src }}"
