---
- name: prepare controlnode for part 3
  hosts: controlnode

  tasks:
    - name: prepare part 3
      copy:
        src: demo-2.py
        dest: /home/vagrant/library/demo.py
      loop_control:
        label: "{{ item.src }}"
