---
- name: configure all nodes
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.common

- name: configure managednode
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.users
      users_user_list:
        - name: ansible
          password: $1$Joris$iJ59LPkmyhcXKBZCtLKpN0

- name: configure controlnode
  hosts: controlnode
  become: yes
  gather_facts: yes

  tasks:
    - name: install required software
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ansible
        - git
        - vim

    - name: install required pip modules
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - pycodestyle
        - mock
        - voluptuous

    - name: configure vim 
      lineinfile:
        path: /home/vagrant/.vimrc
        line: "{{ item }}"
        create: yes
      with_items:
        - set number
        - set expandtab
        - set shiftwidth=4
        - set softtabstop=4
      become: no

    - name: create directories
      file:
        name: "{{ item }}"
        state: directory
      with_items:
        - /home/vagrant/inventory
        - /home/vagrant/library
      become: no

    - name: place files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: ansible.cfg
          dest: /home/vagrant/ansible.cfg
        - src: hosts
          dest: /home/vagrant/inventory/hosts
      become: no
      loop_control:
        label: "{{ item.dest }}"
